### ISSUE TITLE
Code.LoadError with 2.x

### ISSUE THREAD

**Issue by robotvert** [kipcole9/cldr_numbers#6]
Hi,

I'm not sure if this is coming from ex_cldr_numbers or ex_cldr itself but upgrading to 2.x makes my phoenix not compile anymore with Code.LoadError raised randomly (e.g. the error below happens in different files upon several `mix compile` runs)

`mix compile`:
```
== Compilation error in file lib/decapx_web/controllers/pdf_controller.ex ==
** (Code.LoadError) could not load /Users/julien/dev/repos/decapx/deps/postgrex/lib/decapx_web/controllers/pdf_controller.ex
    (elixir) lib/code.ex:1147: Code.find_file/2
    (elixir) lib/code.ex:928: Code.compile_file/2
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

iex gives a bit more info (note the different file):
`iex -S mix`
```
== Compilation error in file lib/decapx/works/chantier.ex ==
** (Code.LoadError) could not load /Users/julien/dev/repos/decapx/deps/ex_cldr/lib/decapx/works/chantier.ex
    (elixir) lib/code.ex:1147: Code.find_file/2
    (elixir) lib/code.ex:928: Code.compile_file/2
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
** (MatchError) no match of right hand side value: {:error, :bad_directory}
    (mix) lib/mix/tasks/compile.all.ex:24: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:39: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.ex:94: Mix.Tasks.Compile.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/tasks/app.start.ex:57: Mix.Tasks.App.Start.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/tasks/run.ex:129: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```
Here are the differences from 1.x to 2.x:

`config/config.exs`
```diff
-config :ex_cldr,
-  default_locale: "fr",
-  locales: ["fr"]
```

`lib/decapx/cldr.ex`
```diff
+defmodule Decapx.Cldr do
+  use Cldr,
+    default_locale: "fr",
+    locales: ["fr"]
+end
```

`mix.exs`
```
-      {:ex_cldr_numbers, "~> 1.0"},
+      {:ex_cldr_numbers, "~> 2.0"},
```

and where I'm using it, the difference is simply `Cldr.Number.to_string` becoming `Decapx.Cldr.Number.to_string`.

Looking around, I found this [issue](https://github.com/elixir-lang/elixir/issues/7699) that looks somewhat similar but it looks like it's been resolved.

Also, I wonder if I need to keep cldr in the compilers list, e.g.
```
compilers: [:phoenix, :gettext] ++ Mix.compilers() ++ [:cldr],
```
(keeping it as is or removing it didn't make any difference)

Running "Erlang/OTP 21 [erts-10.1.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]" and Elixir 1.7.4.

Let me know if you need more info, thanks!

**Comment by kipcole9** [comment]
I'm sorry for the inconvenience.  First, the `:cldr` compiler is definitely not necessary.  Its just a `:noon` now so I recommend removing it.  Its unlikely to be the cause of the error.

I'm not clear what is causing the error. To help a little I wonder if you would mind executing:
* rm -rf _build
* mix deps.compile ex_cldr --force
* mix deps.compile ex_cldr_numbers --force
* iex -S mix

This will hopefully help isolate where the error is combing from.

**Comment by robotvert** [comment]
Thanks for the swift reply!

> Confirm its ex_cldr version 2.0.2

yup

`rm -rf _build` done,

```
mix deps.compile ex_cldr --force
==> ex_cldr
Compiling 1 file (.yrl)
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 25 files (.ex)

== Compilation error in file lib/cldr.ex ==
** (UndefinedFunctionError) function nil.decode!/1 is undefined
    nil.decode!("\"34.0.0\"")
    lib/cldr.ex:62: (module)
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
could not compile dependency :ex_cldr, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_cldr", update it with "mix deps.update ex_cldr" or clean it with "mix deps.clean ex_cldr"
```

then, obviously ex_cldr_numbers is not passing with
```
mix deps.compile ex_cldr_numbers --force
==> ex_cldr_numbers
Compiling 2 files (.yrl)
Compiling 2 files (.xrl)
Compiling 4 files (.erl)
Compiling 22 files (.ex)

== Compilation error in file lib/number/symbol.ex ==
** (CompileError) lib/number/symbol.ex:8: module Cldr is not loaded and could not be found

could not compile dependency :ex_cldr_numbers, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_cldr_numbers", update it with "mix deps.update ex_cldr_numbers" or clean it with "mix deps.clean ex_cldr_numbers"
```

and strangely, this time around `iex -S mix` didn't yield any error or relevant warnings.

FWIW I'm using macOS Mojave and `brew info gettext` yields:
```
brew info gettext
gettext: stable 0.19.8.1 (bottled) [keg-only]
GNU internationalization (i18n) and localization (l10n) library
https://www.gnu.org/software/gettext/
/usr/local/Cellar/gettext/0.19.8.1 (1,934 files, 16.9MB)
  Poured from bottle on 2017-04-15 at 23:34:00
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gettext.rb
```

Totally unfounded speculation but do I need to reinstall gettext? Thinking by seeing the date there, I've done the High Sierra => Mojave upgrade meanwhile, could it be some weird issue at play?

**Comment by kipcole9** [comment]
Hmm, curious.  Quite a difference - and unexpected - error.  

`ex_cldr` requires a `json` library.  Because thats configurable you need to define it yourself.  If you don't already - given its a Phoenix app there usually is one already.  So apologies if this is obvious, but if not already there please add to `mix.exs`
```
defp deps do
  ...
  {:jason, "~> 1.0"},
  ...
end
```
There should have been an error emitted that is more human readable so I will need to check into that.  Any chance you can send me as much of your `config.exs` or `dev.exs` as you are comfortable to post?

**Comment by kipcole9** [comment]
Ah, I can see that the check for a `json`lib is done when generating a backend.  The check needs to be earlier in the compilation process.  I have fixed that on master.

**Comment by robotvert** [comment]
That would explain the weird error when trying to compile individually, now that iex made everything to compile, it's fine:
```
mix deps.compile ex_cldr --force
==> ex_cldr
Compiling 2 files (.erl)
Compiling 25 files (.ex)
Generated ex_cldr app
```

I'll try using master and let you know, sorry I have to run now so can't do it right away.

**Comment by kipcole9** [comment]
Thanks for the feedback.  I wouldn’t worry too much about master, I’ll release an update in my morning since this is a pretty rude introduction to a lib!  Late in my time zone so out too.

**Comment by kipcole9** [comment]
I have published [ex_cldr version 2.0.3](https://hex.pm/packages/ex_cldr/2.0.3) that will detect the lack of a `json` decoder earlier in the compilation phase so you should get a nicer exception message in these cases.  I'm not certain that was the root cause of your initial report so let me know if you see any other issues?
